trayhttpd:
  privileged: true
  volumes:
   - ./www:/var/www/html
  working_dir: /var/www/html
  build: config
  links:
    - redis
  ports:
   - "80:80"
  stdin_open: true
  tty: true
redis:
  image: redis
  ports:
   - "6378:6378"
